bbsCREATE TABLE USER(
userID VARCHAR(20),
userPassword VARCHAR(20),
userName VARCHAR(20) NOT NULL,
userEmail VARCHAR(50),
PRIMARY KEY(userID),
UNIQUE INDEX `userID` (`userID`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE bbs(
bbsID INT,
bbsTitle VARCHAR(50) NOT NULL ,
userID VARCHAR(20) NOT null,
bbsDate DATETIME, 
bbsContent VARCHAR(2048) NOT NULL ,
bbsAvailable INT,
PRIMARY KEY(bbsID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE reply(
bbsrid INT NOT NULL auto_increment,
bbsID INT,
userID VARCHAR(20),
bbsDate DATETIME ,
bbsrmsg VARCHAR(100),
PRIMARY KEY(bbsrid),
CONSTRAINT `message_FK` FOREIGN KEY(`bbsID`) REFERENCES `bbs` (`bbsID`) ON DELETE CASCADE ON UPDATE NO ACTION
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

